apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vda
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vda
    spec:
      containers:
      - name: vda
        image: ahmedeidx/vda
